// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zpgiqvvjrfqnnbvojsvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpwZ2lxdnZqcmZxbm5idm9qc3Z5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxNDQ1MzEsImV4cCI6MjA1OTcyMDUzMX0.klnf9k99jzHR_8vB9mztbIbSoKPF8eWNGtQ2ZdDQjXw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);